#!/bin/bash
climc	 feature-config-aliyun	 --switch on
climc	 feature-config-apsara	 --switch on
climc	 feature-config-auth	 --switch on
climc	 feature-config-aws	 --switch on
climc	 feature-config-azure	 --switch on
climc	 feature-config-baidu	 --switch on
climc	 feature-config-baremetal	 --switch on
climc	 feature-config-bill	 --switch on
climc	 feature-config-bingocloud	 --switch on
climc	 feature-config-ceph	 --switch on
climc	 feature-config-cloudpods	 --switch on
climc	 feature-config-ctyun	 --switch on
climc	 feature-config-cucloud	 --switch on
climc	 feature-config-default	 --switch on
climc	 feature-config-dstack	 --switch on
climc	 feature-config-ecloud	 --switch on
climc	 feature-config-google	 --switch on
climc	 feature-config-hcso	 --switch on
climc	 feature-config-huawei	 --switch on
climc	 feature-config-jdcloud	 --switch on
climc	 feature-config-k8s	 --switch on
climc	 feature-config-ksyun	 --switch on
climc	 feature-config-lb	 --switch on
climc	 feature-config-monitor	 --switch on
climc	 feature-config-nutanix	 --switch on
climc	 feature-config-onecloud	 --switch on
climc	 feature-config-onestack	 --switch on
climc	 feature-config-openstack	 --switch on
climc	 feature-config-oraclecloud	 --switch on
climc	 feature-config-private	 --switch on
climc	 feature-config-proxmox	 --switch on
climc	 feature-config-public	 --switch on
climc	 feature-config-qcloud	 --switch on
climc	 feature-config-qingcloud	 --switch on
climc	 feature-config-s3	 --switch on
climc	 feature-config-storage	 --switch on
climc	 feature-config-ucloud	 --switch on
climc	 feature-config-vmware	 --switch on
climc	 feature-config-volcengine	 --switch on
climc	 feature-config-xsky	 --switch on
climc	 feature-config-zstack	 --switch on
